import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card'; // Importez MatCardModule ici
import { MatStep } from '@angular/material/stepper';
import { MatStepperModule } from '@angular/material/stepper'; // Pour le stepper
import { MatFormFieldModule } from '@angular/material/form-field'; // Pour les champs de formulaire
import { FormsModule } from '@angular/forms';
@Component({
  selector: 'app-simulationclient',
  standalone: true,
  imports: [CommonModule ,FormsModule ,MatCardModule ,MatStep ,MatStepperModule ,MatFormFieldModule],
  templateUrl: './simulationclient.component.html',
  styleUrls: ['./simulationclient.component.css']
})
export class SimulationclientComponent implements OnInit {
  simulationData: any = {
    "id": 23,
    "accountNo": "000000023",
    "status": {
      "id": 100,
      "code": "loanStatusType.submitted.and.pending.approval",
      "value": "Soumis et en attente d'approbation",
      "pendingApproval": true,
      "waitingForDisbursal": false,
      "active": false,
      "closedObligationsMet": false,
      "closedWrittenOff": false,
      "closedRescheduled": false,
      "closed": false,
      "overpaid": false
    },
    "clientId": 9,
    "clientAccountNo": "000000009",
    "clientName": "Anne-Celia MENSAH",
    "clientOfficeId": 1,
    "loanProductId": 1,
    "loanProductName": "Prêt conso",
    "loanProductDescription": "Prêt à la consommation",
    "isLoanProductLinkedToFloatingRate": false,
    "fundId": 1,
    "fundName": "Fond agence central",
    "loanPurposeId": 24,
    "loanPurposeName": "Construction",
    "loanType": {
      "id": 1,
      "code": "accountType.individual",
      "value": "Individual"
    },
    "currency": {
      "code": "USD",
      "name": "US Dollar",
      "decimalPlaces": 2,
      "inMultiplesOf": 0,
      "displaySymbol": "$",
      "nameCode": "currency.USD",
      "displayLabel": "US Dollar ($)"
    },
    "principal": 2000000.000000,
    "approvedPrincipal": 2000000.000000,
    "proposedPrincipal": 2000000.000000,
    "termFrequency": 24,
    "termPeriodFrequencyType": {
      "id": 2,
      "code": "termFrequency.periodFrequencyType.months",
      "value": "Mois"
    },
    "numberOfRepayments": 24,
    "repaymentEvery": 1,
    "repaymentFrequencyType": {
      "id": 2,
      "code": "repaymentFrequency.periodFrequencyType.months",
      "value": "Mois"
    },
    "interestRatePerPeriod": 4.000000,
    "interestRateFrequencyType": {
      "id": 2,
      "code": "interestRateFrequency.periodFrequencyType.months",
      "value": "Par mois"
    },
    "annualInterestRate": 48.000000,
    "isFloatingInterestRate": false,
    "amortizationType": {
      "id": 1,
      "code": "amortizationType.equal.installments",
      "value": "Egal au versement"
    },
    "interestType": {
      "id": 0,
      "code": "interestType.declining.balance",
      "value": "Solde dégressif"
    },
    "interestCalculationPeriodType": {
      "id": 1,
      "code": "interestCalculationPeriodType.same.as.repayment.period",
      "value": "Identique à la période de remboursement"
    },
    "allowPartialPeriodInterestCalcualtion": false,
    "transactionProcessingStrategyId": 1,
    "transactionProcessingStrategyName": "Pénalités, frais, intérêts, montant principal",
    "syncDisbursementWithMeeting": false,
    "timeline": {
      "submittedOnDate": [
        2024,
        10,
        5
      ],
      "submittedByUsername": "adam",
      "submittedByFirstname": "nadia",
      "submittedByLastname": "Adam",
      "expectedDisbursementDate": [
        2024,
        10,
        5
      ],
      "expectedMaturityDate": [
        2026,
        10,
        5
      ]
    },
    "repaymentSchedule": {
      "currency": {
        "code": "USD",
        "name": "US Dollar",
        "decimalPlaces": 2,
        "inMultiplesOf": 0,
        "displaySymbol": "$",
        "nameCode": "currency.USD",
        "displayLabel": "US Dollar ($)"
      },
      "loanTermInDays": 730,
      "totalPrincipalDisbursed": 2000000.00,
      "totalPrincipalExpected": 2000000.00,
      "totalPrincipalPaid": 0.00,
      "totalInterestCharged": 1316695.84,
      "totalFeeChargesCharged": 0.00,
      "totalPenaltyChargesCharged": 0.00,
      "totalWaived": 0.00,
      "totalWrittenOff": 0.00,
      "totalRepaymentExpected": 3316695.84,
      "totalRepayment": 0.00,
      "totalPaidInAdvance": 0.00,
      "totalPaidLate": 0.00,
      "totalOutstanding": 3316695.84,


        },




"periods": [
        


              {
                  "dueDate": [
                      2024,
                      10,
                      5
                  ],
                  "principalDisbursed": 2000000.000000,
                  "principalLoanBalanceOutstanding": 2000000.000000,
                  "feeChargesDue": 0.000000,
                  "feeChargesOutstanding": 0.000000,
                  "totalOriginalDueForPeriod": 0.000000,
                  "totalDueForPeriod": 0.000000,
                  "totalOutstandingForPeriod": 0.000000,
                  "totalActualCostOfLoanForPeriod": 0.000000
              },
              {
                  "period": 1,
                  "fromDate": [
                      2024,
                      10,
                      5
                  ],
                  "dueDate": [
                      2024,
                      11,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 40000.000000,
                  "principalDue": 40000.000000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 40000.000000,
                  "principalLoanBalanceOutstanding": 1960000.000000,
                  "interestOriginalDue": 80000.000000,
                  "interestDue": 80000.000000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 80000.000000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 80000.000000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 2,
                  "fromDate": [
                      2024,
                      11,
                      5
                  ],
                  "dueDate": [
                      2024,
                      12,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 41600.000000,
                  "principalDue": 41600.000000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 41600.000000,
                  "principalLoanBalanceOutstanding": 1918400.000000,
                  "interestOriginalDue": 78400.000000,
                  "interestDue": 78400.000000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 78400.000000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 78400.000000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 3,
                  "fromDate": [
                      2024,
                      12,
                      5
                  ],
                  "dueDate": [
                      2025,
                      1,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 43264.000000,
                  "principalDue": 43264.000000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 43264.000000,
                  "principalLoanBalanceOutstanding": 1875136.000000,
                  "interestOriginalDue": 76736.000000,
                  "interestDue": 76736.000000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 76736.000000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 76736.000000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 4,
                  "fromDate": [
                      2025,
                      1,
                      5
                  ],
                  "dueDate": [
                      2025,
                      2,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 44994.560000,
                  "principalDue": 44994.560000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 44994.560000,
                  "principalLoanBalanceOutstanding": 1830141.440000,
                  "interestOriginalDue": 75005.440000,
                  "interestDue": 75005.440000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 75005.440000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 75005.440000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 5,
                  "fromDate": [
                      2025,
                      2,
                      5
                  ],
                  "dueDate": [
                      2025,
                      3,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 28,
                  "principalOriginalDue": 46794.340000,
                  "principalDue": 46794.340000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 46794.340000,
                  "principalLoanBalanceOutstanding": 1783347.100000,
                  "interestOriginalDue": 73205.660000,
                  "interestDue": 73205.660000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 73205.660000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 73205.660000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 6,
                  "fromDate": [
                      2025,
                      3,
                      5
                  ],
                  "dueDate": [
                      2025,
                      4,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 48666.120000,
                  "principalDue": 48666.120000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 48666.120000,
                  "principalLoanBalanceOutstanding": 1734680.980000,
                  "interestOriginalDue": 71333.880000,
                  "interestDue": 71333.880000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 71333.880000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 71333.880000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 7,
                  "fromDate": [
                      2025,
                      4,
                      5
                  ],
                  "dueDate": [
                      2025,
                      5,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 50612.760000,
                  "principalDue": 50612.760000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 50612.760000,
                  "principalLoanBalanceOutstanding": 1684068.220000,
                  "interestOriginalDue": 69387.240000,
                  "interestDue": 69387.240000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 69387.240000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 69387.240000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 8,
                  "fromDate": [
                      2025,
                      5,
                      5
                  ],
                  "dueDate": [
                      2025,
                      6,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 52637.270000,
                  "principalDue": 52637.270000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 52637.270000,
                  "principalLoanBalanceOutstanding": 1631430.950000,
                  "interestOriginalDue": 67362.730000,
                  "interestDue": 67362.730000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 67362.730000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 67362.730000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 9,
                  "fromDate": [
                      2025,
                      6,
                      5
                  ],
                  "dueDate": [
                      2025,
                      7,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 54742.760000,
                  "principalDue": 54742.760000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 54742.760000,
                  "principalLoanBalanceOutstanding": 1576688.190000,
                  "interestOriginalDue": 65257.240000,
                  "interestDue": 65257.240000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 65257.240000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 65257.240000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 10,
                  "fromDate": [
                      2025,
                      7,
                      5
                  ],
                  "dueDate": [
                      2025,
                      8,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 56932.470000,
                  "principalDue": 56932.470000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 56932.470000,
                  "principalLoanBalanceOutstanding": 1519755.720000,
                  "interestOriginalDue": 63067.530000,
                  "interestDue": 63067.530000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 63067.530000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 63067.530000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 11,
                  "fromDate": [
                      2025,
                      8,
                      5
                  ],
                  "dueDate": [
                      2025,
                      9,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 59209.770000,
                  "principalDue": 59209.770000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 59209.770000,
                  "principalLoanBalanceOutstanding": 1460545.950000,
                  "interestOriginalDue": 60790.230000,
                  "interestDue": 60790.230000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 60790.230000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 60790.230000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 12,
                  "fromDate": [
                      2025,
                      9,
                      5
                  ],
                  "dueDate": [
                      2025,
                      10,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 61578.160000,
                  "principalDue": 61578.160000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 61578.160000,
                  "principalLoanBalanceOutstanding": 1398967.790000,
                  "interestOriginalDue": 58421.840000,
                  "interestDue": 58421.840000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 58421.840000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 58421.840000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 13,
                  "fromDate": [
                      2025,
                      10,
                      5
                  ],
                  "dueDate": [
                      2025,
                      11,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 64041.290000,
                  "principalDue": 64041.290000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 64041.290000,
                  "principalLoanBalanceOutstanding": 1334926.500000,
                  "interestOriginalDue": 55958.710000,
                  "interestDue": 55958.710000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 55958.710000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 55958.710000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 14,
                  "fromDate": [
                      2025,
                      11,
                      5
                  ],
                  "dueDate": [
                      2025,
                      12,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 66602.940000,
                  "principalDue": 66602.940000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 66602.940000,
                  "principalLoanBalanceOutstanding": 1268323.560000,
                  "interestOriginalDue": 53397.060000,
                  "interestDue": 53397.060000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 53397.060000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 53397.060000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 15,
                  "fromDate": [
                      2025,
                      12,
                      5
                  ],
                  "dueDate": [
                      2026,
                      1,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 69267.060000,
                  "principalDue": 69267.060000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 69267.060000,
                  "principalLoanBalanceOutstanding": 1199056.500000,
                  "interestOriginalDue": 50732.940000,
                  "interestDue": 50732.940000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 50732.940000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 50732.940000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 16,
                  "fromDate": [
                      2026,
                      1,
                      5
                  ],
                  "dueDate": [
                      2026,
                      2,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 72037.740000,
                  "principalDue": 72037.740000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 72037.740000,
                  "principalLoanBalanceOutstanding": 1127018.760000,
                  "interestOriginalDue": 47962.260000,
                  "interestDue": 47962.260000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 47962.260000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 47962.260000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 17,
                  "fromDate": [
                      2026,
                      2,
                      5
                  ],
                  "dueDate": [
                      2026,
                      3,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 28,
                  "principalOriginalDue": 74919.250000,
                  "principalDue": 74919.250000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 74919.250000,
                  "principalLoanBalanceOutstanding": 1052099.510000,
                  "interestOriginalDue": 45080.750000,
                  "interestDue": 45080.750000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 45080.750000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 45080.750000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 18,
                  "fromDate": [
                      2026,
                      3,
                      5
                  ],
                  "dueDate": [
                      2026,
                      4,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 77916.020000,
                  "principalDue": 77916.020000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 77916.020000,
                  "principalLoanBalanceOutstanding": 974183.490000,
                  "interestOriginalDue": 42083.980000,
                  "interestDue": 42083.980000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 42083.980000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 42083.980000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 19,
                  "fromDate": [
                      2026,
                      4,
                      5
                  ],
                  "dueDate": [
                      2026,
                      5,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 81032.660000,
                  "principalDue": 81032.660000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 81032.660000,
                  "principalLoanBalanceOutstanding": 893150.830000,
                  "interestOriginalDue": 38967.340000,
                  "interestDue": 38967.340000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 38967.340000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 38967.340000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 20,
                  "fromDate": [
                      2026,
                      5,
                      5
                  ],
                  "dueDate": [
                      2026,
                      6,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 84273.970000,
                  "principalDue": 84273.970000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 84273.970000,
                  "principalLoanBalanceOutstanding": 808876.860000,
                  "interestOriginalDue": 35726.030000,
                  "interestDue": 35726.030000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 35726.030000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 35726.030000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 21,
                  "fromDate": [
                      2026,
                      6,
                      5
                  ],
                  "dueDate": [
                      2026,
                      7,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 87644.930000,
                  "principalDue": 87644.930000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 87644.930000,
                  "principalLoanBalanceOutstanding": 721231.930000,
                  "interestOriginalDue": 32355.070000,
                  "interestDue": 32355.070000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 32355.070000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 32355.070000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 22,
                  "fromDate": [
                      2026,
                      7,
                      5
                  ],
                  "dueDate": [
                      2026,
                      8,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 91150.720000,
                  "principalDue": 91150.720000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 91150.720000,
                  "principalLoanBalanceOutstanding": 630081.210000,
                  "interestOriginalDue": 28849.280000,
                  "interestDue": 28849.280000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 28849.280000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 28849.280000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 23,
                  "fromDate": [
                      2026,
                      8,
                      5
                  ],
                  "dueDate": [
                      2026,
                      9,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 31,
                  "principalOriginalDue": 94796.750000,
                  "principalDue": 94796.750000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 94796.750000,
                  "principalLoanBalanceOutstanding": 535284.460000,
                  "interestOriginalDue": 25203.250000,
                  "interestDue": 25203.250000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 25203.250000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 120000.000000,
                  "totalDueForPeriod": 120000.000000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 120000.000000,
                  "totalActualCostOfLoanForPeriod": 25203.250000,
                  "totalInstallmentAmountForPeriod": 120000.00
              },
              {
                  "period": 24,
                  "fromDate": [
                      2026,
                      9,
                      5
                  ],
                  "dueDate": [
                      2026,
                      10,
                      5
                  ],
                  "complete": false,
                  "daysInPeriod": 30,
                  "principalOriginalDue": 535284.460000,
                  "principalDue": 535284.460000,
                  "principalPaid": 0,
                  "principalWrittenOff": 0,
                  "principalOutstanding": 535284.460000,
                  "principalLoanBalanceOutstanding": 0.000000,
                  "interestOriginalDue": 21411.380000,
                  "interestDue": 21411.380000,
                  "interestPaid": 0,
                  "interestWaived": 0,
                  "interestWrittenOff": 0,
                  "interestOutstanding": 21411.380000,
                  "feeChargesDue": 0,
                  "feeChargesPaid": 0,
                  "feeChargesWaived": 0,
                  "feeChargesWrittenOff": 0,
                  "feeChargesOutstanding": 0,
                  "penaltyChargesDue": 0,
                  "penaltyChargesPaid": 0,
                  "penaltyChargesWaived": 0,
                  "penaltyChargesWrittenOff": 0,
                  "penaltyChargesOutstanding": 0,
                  "totalOriginalDueForPeriod": 556695.840000,
                  "totalDueForPeriod": 556695.840000,
                  "totalPaidForPeriod": 0,
                  "totalPaidInAdvanceForPeriod": 0,
                  "totalPaidLateForPeriod": 0,
                  "totalWaivedForPeriod": 0,
                  "totalWrittenOffForPeriod": 0,
                  "totalOutstandingForPeriod": 556695.840000,
                  "totalActualCostOfLoanForPeriod": 21411.380000,
                  "totalInstallmentAmountForPeriod": 556695.84
              }
          ],
      "disbursementDetails": [],
      "feeChargesAtDisbursementCharged": 0.000000,
      "multiDisburseLoan": false,
      "canDefineInstallmentAmount": false,
      "canDisburse": false,
      "emiAmountVariations": [],
      "canUseForTopup": false,
      "isTopup": false,
      "closureLoanId": 0,
      "inArrears": false,
      "isNPA": false,
      "overdueCharges": [],
      "daysInMonthType": {
          "id": 1,
          "code": "DaysInMonthType.actual",
          "value": "Actuel"
      },
      "daysInYearType": {
          "id": 1,
          "code": "DaysInYearType.actual",
          "value": "Actuel"
      },
      "isInterestRecalculationEnabled": false,
      "createStandingInstructionAtDisbursement": false,
      "paidInAdvance": {
          "paidInAdvance": 0
      },
      "isVariableInstallmentsAllowed": false,
      "minimumGap": 0,
      "maximumGap": 0,
      "isEqualAmortization": false,
      "isRatesEnabled": false
    // Fin de l'objet JSON



};

    // URL de l'API pour récupérer les données de simulation
    private apiUrl = 'https://fingiciel.ngrok.io/fineract-provider/api/v1/loans/23?associations=all&exclude=guarantors,futureSchedule';

    constructor(private http: HttpClient) {}

    ngOnInit(): void {
      this.fetchSimulationData();
    }

    // Fonction pour récupérer les données depuis l'API
    fetchSimulationData(): void {
      this.http.get(this.apiUrl).subscribe(
        (data) => {
          this.simulationData = data; // Assigner les données récupérées à simulationData
        },
        (error) => {
          console.error('Erreur lors de la récupération des données', error);
        }
      );
    }
  }
